name: flutterfire_cli
description: A command-line application for FlutterFire.
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ansi_styles: ^0.3.0
  args: ^2.3.0
  file: ^6.1.2
  path: ^1.8.0

dev_dependencies:
  test: ^1.16.0

executables:
  flutterfire: