name: FlutterFireCLI
repository: https://github.com/invertase/flutterfire_cli
packages:
  - packages/**
  - "*"

scripts:
  analyze:
    run: melos exec -c 1 -- "dart analyze . --fatal-infos"
    description: Run dart analyzer in a specific package.
    select-package:
      ignore:
        - "*monorepo*"

  test:
    description: Run tests in a specific package.
    run: melos exec --concurrency=1 -- "dart pub get && dart pub run test --reporter expanded"
    select-package:
      dir-exists:
        - "test/"
      scope:
        - flutterfire_cli

  format: dart format -o write .
  version: dart run scripts/generate_version.dart && git add packages/flutterfire_cli/lib/version.g.dart
